language: ruby

sudo: false

rvm:
  - 2.5.1

cache:
  bundler: true

addons:
  firefox: "60.0.1"

before_install:
  # Install geckodriver from https://github.com/mozilla/geckodriver/releases
  - mkdir -p tmp/geckodriver
  - curl -f -L -o geckodriver-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - tar xf geckodriver-linux64.tar.gz -C tmp/geckodriver
  - export PATH=${PWD}/tmp/geckodriver:$PATH
  - geckodriver --version

env:
  global:
    - USE_HEADLESS=true

script:
  # ref: https://jenkins.magellanic-clouds.com/job/TakeruUshio/job/selenium_test/
  - bundle exec rspec spec/features/*.feature

