language: ruby

sudo: false

rvm:
  - 2.5.3

cache:
  bundler: true

addons:
  # https://docs.travis-ci.com/user/firefox
  firefox: latest
  # https://docs.travis-ci.com/user/chrome
  chrome: stable

before_install:
  # check firefox version
  - firefox --version
  # check chrome version
  - google-chrome --version
  # Install geckodriver from https://github.com/mozilla/geckodriver/releases
  - mkdir -p tmp/geckodriver
  - curl -f -L -o geckodriver-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar xf geckodriver-linux64.tar.gz -C tmp/geckodriver
  - export PATH=${PWD}/tmp/geckodriver:$PATH
  - geckodriver --version
  # Install chromedriver from http://chromedriver.chromium.org/downloads
  - mkdir -p tmp/chromedriver
  - curl -f -L -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  - unzip -d tmp/chromedriver chromedriver_linux64.zip
  - export PATH=${PWD}/tmp/chromedriver:$PATH
  - chromedriver --version

env:
  global:
    - USE_HEADLESS=true
    # about test-queue (exec/rspec-queue.rb) environment variable, see https://github.com/tmm1/test-queue#environment-variables
    - TEST_QUEUE_WORKERS=4

script:
  # ref: https://jenkins.magellanic-clouds.com/job/TakeruUshio/job/selenium_test/
  - bundle exec rspec spec/features/ || bundle exec rspec spec/features/ --only-failures
  - rm tmp/example_status.txt
  - bundle exec exec/rspec-queue.rb spec/features/ || bundle exec exec/rspec-queue.rb spec/features/ --only-failures

