language: ruby

sudo: false

rvm:
  - 2.5.1

cache:
  bundler: true

addons:
  firefox: "60.0.2"
  chrome: stable

before_install:
  # Install geckodriver from https://github.com/mozilla/geckodriver/releases
  - mkdir -p tmp/geckodriver
  - curl -f -L -o geckodriver-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar xf geckodriver-linux64.tar.gz -C tmp/geckodriver
  - export PATH=${PWD}/tmp/geckodriver:$PATH
  - geckodriver --version
  # Install chromedriver from http://chromedriver.chromium.org/downloads
  - mkdir -p tmp/chromedriver
  - curl -f -L -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  - unzip -d tmp/chromedriver chromedriver_linux64.zip
  - export PATH=${PWD}/tmp/chromedriver:$PATH
  - chromedriver --version

env:
  global:
    - USE_HEADLESS=true

script:
  # ref: https://jenkins.magellanic-clouds.com/job/TakeruUshio/job/selenium_test/
  - bundle exec rspec spec/features/*.feature

