language: ruby

sudo: false

rvm:
  - 2.5.1

cache:
  bundler: true

addons:
  firefox: "60.0.1"

script:
  # ref: https://jenkins.magellanic-clouds.com/job/TakeruUshio/job/selenium_test/
  - xvfb-run bundle exec rspec spec/features/*.feature

