# https://docs.travis-ci.com/user/reference/overview/
dist: xenial

language: ruby

rvm:
  - 2.6

gemfile:
  - gemfiles/selenium_3.gemfile
  - gemfiles/selenium_4.gemfile

cache:
  bundler: true

addons:
  # https://docs.travis-ci.com/user/firefox
  firefox: latest
  # https://docs.travis-ci.com/user/chrome
  chrome: stable

before_install:
  # Install bundler 2 (https://docs.travis-ci.com/user/languages/ruby/#bundler)
  - gem update --system
  - gem install bundler
  # check firefox version
  - firefox --version
  # check chrome version
  - google-chrome --version
  # Install geckodriver from https://github.com/mozilla/geckodriver/releases
  - mkdir -p tmp/geckodriver
  - curl -f -L -o geckodriver-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar xf geckodriver-linux64.tar.gz -C tmp/geckodriver
  - export PATH=${PWD}/tmp/geckodriver:$PATH
  - geckodriver --version
  # Install chromedriver from http://chromedriver.chromium.org/downloads
  - mkdir -p tmp/chromedriver
  - curl -f -L -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip
  - unzip -d tmp/chromedriver chromedriver_linux64.zip
  - export PATH=${PWD}/tmp/chromedriver:$PATH
  - chromedriver --version

env:
  global:
    - USE_HEADLESS=true

script:
  # ref: https://jenkins.magellanic-clouds.com/job/TakeruUshio/job/selenium_test/
  - bundle exec rspec spec/features/ || bundle exec rspec spec/features/ --only-failures
