# https://dependabot.com/blog/introducing-config-files/
version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "TakeruUshio"
