#
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions
#

name: CI

on: [push]

jobs:
  dump:
    name: Dump env vars, contexts
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Environment Variables
        run: export -p
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  test:
    name: Test
    strategy:
      matrix:
        ruby_version:
          - 2.6.x
          - 2.7.x
        gemfile:
          - Gemfile
          - gemfiles/selenium_3.gemfile
          - gemfiles/selenium_4.gemfile
      fail-fast: false
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Check ruby version and gems
        run: |
          set -x
          ruby --version
          gem env
          gem list
      - name: Install latest bundler
        run: |
          set -x
          gem install bundler
          gem list -e bundler
          bundle --version
      - name: Check firefox and install geckodriver
        run: |
          set -x
          firefox --version
          if geckodriver --version 2>/dev/null; then
            :
          else
            mkdir -p tmp
            curl -sSfL -o tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
            tar xf tmp/geckodriver.tar.gz -C tmp
            sudo install -m 755 -o root -g root -p tmp/geckodriver /usr/local/bin/geckodriver
            geckodriver --version
          fi
      - name: Check google-chrome and install chromedriver
        run: |
          set -x
          google-chrome --version
          if chromedriver --version 2>/dev/null; then
            :
          else
            mkdir -p tmp
            curl -sSfL -o tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip
            unzip -x tmp/chromedriver_linux64.zip -d tmp
            sudo install -m 755 -o root -g root -p tmp/chromedriver /usr/local/bin/chromedriver
            chromedriver --version
          fi
      - name: Set Gemfile location
        run: bundle config gemfile ${{ matrix.gemfile }}
        if: matrix.gemfile != 'Gemfile'
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run test
        run: bundle exec rspec spec/features/ || bundle exec rspec spec/features/ --only-failures
        env:
          USE_HEADLESS: 'true'

